### ISSUE TITLE
Magalix action generates SARIF with an invalid endColumn property

### ISSUE THREAD

**Issue by simon-engledew** [MagalixCorp/magalix-action#1]
According to the SARIF specification, `runs[].results[].locations[].physicalLocation.region.endColumn` must be an integer of 1 or more:

https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html#_Ref493491342

Currently the Magalix action is generating incorrect regions, e.g:

```
"region": {
  "endLine": 48,
  "startColumn": 1,
  "endColumn": 0,
  "startLine": 25
}
```

**Comment by josepalafox** [comment]
Please see our guide to integrating with GitHub Code Scanning as it provides a number of tools and hints to making this an awesome end user experience.

https://partner.github.com/integration-resources/2021/03/09/pattern-integrating-with-code-scanning.html

Once you are done you can make a PR to add your integration from the GitHub Marketplace into the GitHub UI. See this example: https://github.com/actions/starter-workflows/pull/832

**Comment by simon-engledew** [comment]
Hi, sorry! I am actually from the GitHub Code Scanning team. 🙇 I am trying to report a bug in the SARIF output of the Magalix tool. Is this the right place?

**Comment by simon-engledew** [comment]
I'll close this issue as inactive. We hope to start rejecting invalid sarif documents in future, at which point this error will appear in the user interface.
